-- =========================================================
-- Optional sample data for manual MySQL setup.
-- NOTE: The application already seeds this same data
-- automatically on first run via DataInitializer.java,
-- so running this script is only needed if you disabled
-- the automatic seeder and want sample records via SQL.
-- Passwords below are BCrypt hashes of: Admin@123 / Doctor@123 / Reception@123
-- =========================================================

USE hospital_management_db;

INSERT INTO users (username, email, password, full_name, role, enabled, created_at) VALUES
('admin', 'admin@hms.local', '$2a$10$7EqJtq98hPqEX7fNZaFWoOa6Y6z6R1V6qk7z6qk7z6qk7z6qk7z6q', 'System Administrator', 'ADMIN', TRUE, NOW()),
('doctor', 'doctor@hms.local', '$2a$10$7EqJtq98hPqEX7fNZaFWoOa6Y6z6R1V6qk7z6qk7z6qk7z6qk7z6q', 'Dr. Sarah Mitchell', 'DOCTOR', TRUE, NOW()),
('reception', 'reception@hms.local', '$2a$10$7EqJtq98hPqEX7fNZaFWoOa6Y6z6R1V6qk7z6qk7z6qk7z6qk7z6q', 'Front Desk Receptionist', 'RECEPTIONIST', TRUE, NOW());
-- NOTE: replace the password hashes above with real BCrypt hashes generated by the app
-- (the automatic DataInitializer already does this correctly for you).

INSERT INTO doctors (first_name, last_name, email, phone_number, specialization, department, years_of_experience, consultation_fee, available, created_at) VALUES
('Sarah', 'Mitchell', 'sarah.mitchell@hms.local', '+1-202-555-0101', 'Cardiology', 'Cardiology', 12, 150.00, TRUE, NOW()),
('James', 'Carter', 'james.carter@hms.local', '+1-202-555-0102', 'Orthopedics', 'Orthopedics', 9, 120.00, TRUE, NOW()),
('Emily', 'Nguyen', 'emily.nguyen@hms.local', '+1-202-555-0103', 'Pediatrics', 'Pediatrics', 6, 100.00, TRUE, NOW()),
('Michael', 'Okafor', 'michael.okafor@hms.local', '+1-202-555-0104', 'Neurology', 'Neurology', 15, 180.00, FALSE, NOW());

INSERT INTO patients (first_name, last_name, email, phone_number, date_of_birth, gender, address, blood_group, emergency_contact, created_at) VALUES
('John', 'Smith', 'john.smith@example.com', '+1-303-555-0111', '1985-04-12', 'MALE', '123 Maple Street, Denver, CO', 'O+', '+1-303-555-0199', NOW()),
('Emma', 'Johnson', 'emma.johnson@example.com', '+1-303-555-0112', '1992-08-25', 'FEMALE', '456 Oak Avenue, Denver, CO', 'A-', '+1-303-555-0198', NOW()),
('Liam', 'Davis', 'liam.davis@example.com', '+1-303-555-0113', '2015-01-30', 'MALE', '789 Pine Road, Denver, CO', 'B+', '+1-303-555-0197', NOW()),
('Olivia', 'Martinez', 'olivia.martinez@example.com', '+1-303-555-0114', '1978-11-03', 'FEMALE', '321 Birch Lane, Denver, CO', 'AB+', '+1-303-555-0196', NOW());
